name: Self-Hosted Runner Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # webhook 이벤트에 대한 응답도 추가
  repository_dispatch:
    types: [webhook-trigger]

jobs:
  build:
    runs-on: self-hosted  # self-hosted runner 사용 지정
    steps:
      - name: Send test webhook
        shell: cmd
        run: |
          echo "Sending test webhook to local server..."
          curl -X POST ^
            -H "Content-Type: application/json" ^
            -H "X-GitHub-Event: push" ^
            -H "X-GitHub-Delivery: test-delivery-id" ^
            -d "{\"repository\":{\"full_name\":\"DaeHyeonGO/test\"},\"action\":\"test\"}" ^
            http://localhost:8000/webhook
      
      - name: Check server logs
        shell: cmd
        run: |
          echo "Checking server logs..."
          type nul > webhook_test.log
          timeout /t 2
          type webhook_test.log
  