name: Webhook Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  repository_dispatch:
    types: [webhook-trigger]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Send webhook
        shell: cmd
        run: >
          curl.exe -X POST 
          -H "Content-Type: application/json" 
          -H "X-GitHub-Event: push" 
          -H "X-GitHub-Delivery: ${{ github.run_id }}" 
          -d "{\"ref\":\"${{ github.ref }}\",\"repository\":{\"full_name\":\"${{ github.repository }}\"},\"pusher\":{\"name\":\"${{ github.actor }}\"},\"commits\":${{ toJson(github.event.commits) }}}" 
          http://localhost:8000/webhook
      
      - name: Check server logs
        shell: cmd
        run: |
          echo "Checking server logs..."
          timeout /t 2
          type webhook_test.log