name: Webhook Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  repository_dispatch:
    types: [webhook-trigger]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Send webhook
        shell: cmd
        run: >
          curl.exe -X POST 
          -H "Content-Type: application/json" 
          -H "X-GitHub-Event: push" 
          -H "X-GitHub-Delivery: ${{ github.run_id }}" 
          -H "User-Agent: GitHub-Hookshot/044aadd" 
          -d "{
            \"ref\": \"${{ github.ref }}\",
            \"before\": \"${{ github.event.before }}\",
            \"after\": \"${{ github.event.after }}\",
            \"repository\": {
              \"id\": ${{ github.repository_id }},
              \"name\": \"${{ github.event.repository.name }}\",
              \"full_name\": \"${{ github.repository }}\",
              \"owner\": {
                \"name\": \"${{ github.repository_owner }}\",
                \"email\": \"${{ github.event.pusher.email }}\",
                \"login\": \"${{ github.repository_owner }}\"
              }
            },
            \"pusher\": {
              \"name\": \"${{ github.actor }}\",
              \"email\": \"${{ github.event.pusher.email }}\"
            },
            \"commits\": ${{ toJson(github.event.commits) }},
            \"head_commit\": ${{ toJson(github.event.head_commit) }}
          }" 
          http://localhost:8000/webhook
      
      - name: Check server logs
        shell: cmd
        run: |
          echo "Checking server logs..."
          timeout /t 2
          type webhook_test.log